name: Docker Image Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check workflow file
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              JSON.parse(fs.readFileSync('path/to/your/workflow/file', 'utf8'))
              process.env.WORKFLOW_STATUS = 'success'
            } catch (error) {
              console.log('Error:', error)
              process.env.WORKFLOW_STATUS = 'failure'
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
