name: Publish Docker Image

on:
  release:
    types: [published]

env:
  IMAGE_NAME: lemp
  GITHUB_USERNAME: ${{ github.repository_owner }}
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}, ${{ env.IMAGE_NAME }}:latest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}, ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker image to GitHub Package Registry
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }} ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          docker push ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:latest
